#!/bin/bash
#Enable NAT

ERRORUSG=100
ERRORROOT=101
if [ $EUID != 0 ]; then
	echo "Error: root privilege needed"
	exit $ERRORROOT
fi
if [ $# != 2 ]
then
	echo "Usage: `basename $0` IN OUT"
	exit $ERRORUSG
fi

IN=$1
OUT=$2
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables --table nat --append POSTROUTING --out-interface OUT -j MASQUERADE
iptables --append FORWARD --in-interface IN -j ACCEPT

#Thanks to lorenzo
#Uncomment the line below if facing problems while sharing PPPoE
#iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
 
sysctl -w net.ipv4.ip_forward=1
